jaj/Controllers/videoListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using jaj.Models;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;

namespace jaj.Controllers
{
    public class videoListController : Controller
    {

        DbBaza db = new DbBaza();
        // GET: videoList
        public ActionResult Index()
        {
            List<video> videolist = new List<video>();
          
            using (DbBaza db = new DbBaza())
            {
                videolist = db.videoFile.ToList();
            }

                return View(videolist);
        }

        [HttpGet]
        public ActionResult videoPage(int id)
        {
            video videoModel = new video();

            using (DbBaza db = new DbBaza())
            {
                videoModel = db.videoFile.Where(x => x.videoID == id).FirstOrDefault();
            }

            return View(videoModel);
        }
    }
}

jaj/Views/Shared/_Layout.cshtml
@using jaj.Misc
<!DOCTYPE html>
<html>
<head>
    <!-- Potrebni meta tagovi -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Team o7</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-dark bg-info">
        <div class="row-sm-3">
            <a class="navbar-brand" href="/videoList/Index">Team 7</a>


        </div>
        <div class="row-sm-3">
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="">
                <button class="btn btn-warning my-2 my-sm-0" type="submit">Traži</button>
            </form>
        </div>


        <div class="row-sm-3">

            @if (!User.Identity.IsAuthenticated)
            {

            }
            else
            {
                <div class="col-md-6">
                    <div class="username-style">
                        <a> @Html.ActionLink(((User as LoggedInUser).Username), "Index", "videoList")</a>
                    </div>
                </div>
                <div class="col-md-6">
                    <img src="@Url.Content((User as LoggedInUser).profilePicture)" style="width:48px; height:48px;" />
                </div>
            }

           </div>




                <div class="row-sm-3">
                    <div class="menu-wrap">
                        <input type="checkbox" class="toggler">
                        <div class="hamburger"><div></div></div>
                        <div class="menu">
                            <div>
                                <div>
                                    <ul>
                                        <li><a href="/videoList/Index">Home</a></li>

                                        @if (!User.Identity.IsAuthenticated)
                                        {

                                            <li><a href="/User/Registration">Register</a></li>
                                            <li><a href="/User/Login">Login</a></li>
                                        }
                                        else
                                        {
                                            <li><a href="#">Profile</a></li>
                                            <li><a href="#">Upload</a></li>
                                            <li><a href="#">Favorites</a></li>
                                            <li><a href="#">Settings</a></li>
                                            <li><a href="/User/Edit">Edit profile</a></li>
                                            <li>@Html.ActionLink("Logout", "Logout", "User")</li>
                                        }

                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
</nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
        </footer>
    </div>

    <footer id="footer"><p>&copy; @DateTime.Now.Year - Team7</p></footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>